### ISSUE TITLE
Viya and CAS version compatibility

### ISSUE THREAD

**Issue by michburger** [sassoftware/restaf#118]
Dear restaf support,
can you please tell  or describe what version of restaf is compatible with
- Viya 3.5
- Viya 2024.02

**Comment by devaKumaraswamy** [comment]
Recommend using the version with a tag of next. (the current version is 5.2.3.  
It should work with 2024.02

On 3.5:
Viya 3.5 and Viya 4 are quite a bit different but the api's have stayed the same.
The major changes to restaf has been in the area of security(CORS, CSRF etc...)  that were dictated by the Viya requirements in these areas. My goal was to absorb the differences transparently. I am getting a Viya 3.5 instance and will test it out over the next day or so.

Can I ask what is your scenario for using restaf?

Cheers...
Deva

I have to admit that I have not had a chance to test the latest restaf against Viya 3.5. - in theory 5.2.3 should work against 3.5 but theories are not facts.
I am spinning up a Viya 3.5 version to verify that. Will let you know soon.

**Comment by michburger** [comment]
Dear Deva,
thanks a lot for the quick answer!

We've been using restaf for a while in some Viya 3.5 VA dashboards typically for allowing users to write back some (few) parameter values to CAS or to a SAS 9.4 STP.
Now we're about to migrate all dashboards to Viya (4) and unlike before we had a compatibility issues with restaf 1.5.4 towards Viya 2023.12.

Now for future migrations and compatibilities, we're interested how to find out when it is time to change the restaf version and what effort we have during such updates - especially whether our calls towards restaf need to be migrated for the newest restaf.

Now out of our migration interest, we're also interested whether we can simply update the restaf library still for the one Viya 3.5 source system in the time period before we start migrating this one, too.

If I understand you behind the lines, there is no specific compatibility matrix and with some luck, the newest version could be working with our Viya 3.5 system. It is not that critical for us as if there is no further issue, we should be able to migrate all by March this year and thus stop having a 3.5 instance.

**Comment by devaKumaraswamy** [comment]
The goal is always to maintain backward compatibility. If it is broken I will give it the highest priority.

I did not want to leave with the impression that it is "luck".  The main api has not changed.

 The only concerns I have is whether I have handled all the cases where Viya has new features but not Viya 3.5. I always add checks to be backward compatible.

 In particular the code has to handle csrf tokens a bit differently. Also there are some special handling of the csrf equivalent in CAS server that was introduced in Viya 4 that required additional handling. Some of the previous issues you have with upgrading was related to CAS.

You can simply change the version to 5.2.3 and try it. 

The only cas related issue I should point out.
Always pass this option for initStore. This was one of the issues that caused many issues earlier on.

let store = restaf.initStore({casProxy: true});

Also take a look at this link https://sassoftware.github.io/restaf/tutorial-usefulTips.html. But ignore the notes on changing the cas server cors. It is  handled differently in 2024.x

I will keep a close watch on this thread in case you respond.

**Comment by devaKumaraswamy** [comment]
I had a access to a 3.5 instance for a short while yesterday.

**Comment by devaKumaraswamy** [comment]
@michburger 
Did not realize that I accidentally closed the issue. So I have reopened it. I had time yesterday to try the new version on a 3.5 and it seemed to work. I will do some more extensive testing today.
Sorry about that over-eager closing of the issue.
Deva

**Comment by devaKumaraswamy** [comment]
I did further testing. You should be able to switch to 5.2.3 even on Viya 3.5 without any changes.
Please let me know if you run into issues.

**Comment by michburger** [comment]
Dear Deva,no worries, we will report you after our small updates on the second set of reports, only about 20 are using restaf intensively.Kind regards from Erlangen Michael Burger SoftMatch.net
-------- Ursprüngliche Nachricht --------Von: devakumaraswamy ***@***.***> Datum: 21.02.24  17:50  (GMT+01:00) An: sassoftware/restaf ***@***.***> Cc: michburger ***@***.***>, Mention ***@***.***> Betreff: Re: [sassoftware/restaf] Viya and CAS version compatibility (Issue #118) 
@michburger
Did not realize that I accidentally closed the issue. So I have reopened it. I had time yesterday to try the new version on a 3.5 and it seemed to work. I will do some more extensive testing today.
Sorry about that over-eager closing of the issue.
Deva

**Comment by devaKumaraswamy** [comment]
@michburger  Thanks. I will leave this issue open pending your testing. Cheers... Deva

**Comment by devaKumaraswamy** [comment]
@michburger  can I close this now?

**Comment by michburger** [comment]
Dear @devaKumaraswamy , yes, you can: We've also tested on our SAS Viya 3.5 environment and all works like a charm! Thanks for asking and thanks a lot for your support!
